/**
 * PEN-1305 Layer 1 — enforced pre-execution block for full-environment dumps.
 *
 * Background: agent heartbeats repeatedly ran unrestricted environment
 * inspection (`env` / `printenv` / `set` / `export -p` / `declare -x` /
 * `cat /proc/<pid>/environ`), dumping live secret-bearing runtime variables into
 * the run transcript. The Paperclip server ships a transcript-redaction layer
 * (defense-in-depth, catches the persisted values), but the *preventive*
 * command guard (`classifyAgentShellCommand`) was never wired into a runtime
 * hook — so agents kept running the dumps and self-reporting incidents.
 *
 * This module wires that block into the claude_k8s runtime via a Claude Code
 * `PreToolUse` hook. Hooks fire even under `--dangerously-skip-permissions`
 * (which Job pods use, since there is no human to answer permission prompts),
 * so this is the correct enforcement point for unattended runs.
 *
 * The classification logic mirrors the server's `server/src/agent-shell-guard.ts`;
 * `env-guard.test.ts` locks the two in behavioural parity. Keep them in
 * lockstep when either changes.
 */

export type AgentShellCommandDecision =
  | { action: "allow"; reason: "safe_env_inspection" | "not_environment_dump" }
  | { action: "block"; reason: "full_environment_dump" };

const SAFE_ENV_INSPECTION_RE =
  /(?:^|[\s;&|()])(?:\.\/scripts\/safe-env-inspect\.mjs|scripts\/safe-env-inspect\.mjs|safe-env-inspect|paperclip-safe-env)(?:\s|$)/;

const SHELL_WRAPPER_RE = /^(?:\/bin\/)?(?:ba|z|)?sh\s+-l?c\s+(["'])([\s\S]*)\1\s*$/;

const FULL_ENV_DUMP_RE = new RegExp(
  [
    String.raw`(?:^|[;&|]\s*)(?:command\s+)?(?:\/usr\/bin\/)?(?:env|printenv)(?:\s*(?:[;&|]|$))`,
    String.raw`(?:^|[;&|]\s*)(?:set)(?:\s*(?:[;&|]|$))`,
    String.raw`(?:^|[;&|]\s*)export\s+-p(?:\s*(?:[;&|]|$))`,
    String.raw`(?:^|[;&|]\s*)declare\s+-x(?:\s*(?:[;&|]|$))`,
    String.raw`(?:^|[;&|]\s*)cat\s+\/proc\/(?:self|\d+)\/environ(?:\s*(?:[;&|]|$))`,
    String.raw`\/proc\/(?:self|\d+)\/environ`,
  ].join("|"),
  "i",
);

function unwrapShell(command: string): string {
  let current = command.trim();
  for (let i = 0; i < 3; i += 1) {
    const match = SHELL_WRAPPER_RE.exec(current);
    if (!match) return current;
    current = match[2] ?? current;
  }
  return current;
}

/**
 * Classify an agent shell command. `block` for a full-environment dump; `allow`
 * for the allowlisted names-only helper or any non-dump command.
 */
export function classifyAgentShellCommand(command: string): AgentShellCommandDecision {
  const normalized = unwrapShell(command).trim();
  if (!normalized) return { action: "allow", reason: "not_environment_dump" };
  if (SAFE_ENV_INSPECTION_RE.test(normalized)) return { action: "allow", reason: "safe_env_inspection" };
  if (FULL_ENV_DUMP_RE.test(normalized)) return { action: "block", reason: "full_environment_dump" };
  return { action: "allow", reason: "not_environment_dump" };
}

/**
 * Standalone, zero-dependency Node script written into the agent pod and
 * invoked by the Claude Code PreToolUse hook. Reads the hook event JSON on
 * stdin; on a Bash full-environment dump it writes a value-free reason to
 * stderr and exits 2 (Claude Code blocks the tool and feeds stderr to the
 * model). Any parse/other error fails OPEN (exit 0) so the guard can never
 * wedge a run — the server-side redaction layer remains the backstop.
 *
 * Authored with regex *literals* (not `new RegExp(...)`) so the surrounding
 * `String.raw` preserves single backslashes verbatim — no double-escaping, no
 * backticks. Keep behaviourally identical to `classifyAgentShellCommand`
 * above; `env-guard.test.ts` runs the same command corpus through both.
 */
export const ENV_GUARD_SCRIPT = String.raw`#!/usr/bin/env node
// paperclip-env-guard.mjs — PEN-1305 Layer 1 PreToolUse guard. Generated by
// paperclip-adapter-claude-k8s; do not edit in the pod.
const SAFE_ENV_INSPECTION_RE =
  /(?:^|[\s;&|()])(?:\.\/scripts\/safe-env-inspect\.mjs|scripts\/safe-env-inspect\.mjs|safe-env-inspect|paperclip-safe-env)(?:\s|$)/;
const SHELL_WRAPPER_RE = /^(?:\/bin\/)?(?:ba|z|)?sh\s+-l?c\s+(["'])([\s\S]*)\1\s*$/;
const FULL_ENV_DUMP_RE = /(?:^|[;&|]\s*)(?:command\s+)?(?:\/usr\/bin\/)?(?:env|printenv)(?:\s*(?:[;&|]|$))|(?:^|[;&|]\s*)(?:set)(?:\s*(?:[;&|]|$))|(?:^|[;&|]\s*)export\s+-p(?:\s*(?:[;&|]|$))|(?:^|[;&|]\s*)declare\s+-x(?:\s*(?:[;&|]|$))|(?:^|[;&|]\s*)cat\s+\/proc\/(?:self|\d+)\/environ(?:\s*(?:[;&|]|$))|\/proc\/(?:self|\d+)\/environ/i;
function unwrapShell(command) {
  let current = String(command || "").trim();
  for (let i = 0; i < 3; i += 1) {
    const match = SHELL_WRAPPER_RE.exec(current);
    if (!match) return current;
    current = match[2] != null ? match[2] : current;
  }
  return current;
}
function isFullEnvDump(command) {
  const normalized = unwrapShell(command).trim();
  if (!normalized) return false;
  if (SAFE_ENV_INSPECTION_RE.test(normalized)) return false;
  return FULL_ENV_DUMP_RE.test(normalized);
}
let raw = "";
process.stdin.on("data", (d) => { raw += d; });
process.stdin.on("end", () => {
  try {
    const evt = JSON.parse(raw || "{}");
    const tool = evt.tool_name || evt.toolName || "";
    const input = evt.tool_input || evt.toolInput || {};
    const command = input.command || input.cmd || "";
    if (/^(?:Bash|Shell)$/i.test(String(tool)) && command && isFullEnvDump(String(command))) {
      const home = process.env.HOME || "/paperclip";
      process.stderr.write(
        "Blocked by Paperclip env-guard (PEN-1305): full-environment dumps " +
          "(env/printenv/set/export -p/declare -x/cat /proc/*/environ) are disallowed " +
          "because they leak secret-bearing runtime variables into the run transcript. " +
          "To inspect environment variable NAMES safely, run: node " +
          home + "/.claude/safe-env-inspect.mjs\n",
      );
      process.exit(2);
    }
  } catch (_e) {
    // Fail open: never wedge a run on guard error; server-side redaction backstops.
  }
  process.exit(0);
});
`;

/**
 * Names-only environment inspection helper — the allowlisted alternative the
 * guard whitelists (`safe-env-inspect`). Prints variable NAMES, never values.
 */
export const SAFE_ENV_INSPECT_SCRIPT = String.raw`#!/usr/bin/env node
// safe-env-inspect.mjs — PEN-1305 allowlisted env inspection: NAMES ONLY, never values.
for (const name of Object.keys(process.env).sort()) console.log(name);
`;

/**
 * Idempotent settings-merge script (runs via `node -`). Adds a Bash-matcher
 * PreToolUse hook to the runtime's `settings.json` only if an identical command
 * entry is not already present, preserving any existing hooks (e.g. Claude
 * Code's installed Stop hook).
 */
const SETTINGS_MERGE_SCRIPT = String.raw`const fs=require("fs"),p=require("path");const dir=process.env.CLAUDE_CONFIG_DIR||(process.env.HOME||"/paperclip")+"/.claude";const f=p.join(dir,"settings.json");let s={};try{s=JSON.parse(fs.readFileSync(f,"utf8"))||{}}catch(e){}if(typeof s!=="object"||s===null)s={};s.hooks=s.hooks||{};const list=Array.isArray(s.hooks.PreToolUse)?s.hooks.PreToolUse:[];const cmd="node "+p.join(dir,"paperclip-env-guard.mjs");const has=list.some(g=>g&&Array.isArray(g.hooks)&&g.hooks.some(h=>h&&h.command===cmd));if(!has)list.push({matcher:"Bash",hooks:[{type:"command",command:cmd}]});s.hooks.PreToolUse=list;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(f,JSON.stringify(s,null,2));`;

/**
 * Build a `;`-joinable shell fragment that installs the guard + safe helper and
 * merges the PreToolUse hook into `settings.json`. Scripts are base64-embedded
 * so arbitrary JS survives `sh -c` with no quoting hazard. Runs in the MAIN
 * container (which has `node`; the init container is busybox). Fails open on
 * merge error so it can never block a run from starting.
 */
export function buildEnvGuardSetupShell(): string {
  const guardB64 = Buffer.from(ENV_GUARD_SCRIPT, "utf8").toString("base64");
  const helperB64 = Buffer.from(SAFE_ENV_INSPECT_SCRIPT, "utf8").toString("base64");
  const mergeB64 = Buffer.from(SETTINGS_MERGE_SCRIPT, "utf8").toString("base64");
  return [
    `GUARD_DIR="\${CLAUDE_CONFIG_DIR:-\$HOME/.claude}"`,
    `mkdir -p "\$GUARD_DIR"`,
    `printf %s '${guardB64}' | base64 -d > "\$GUARD_DIR/paperclip-env-guard.mjs"`,
    `printf %s '${helperB64}' | base64 -d > "\$GUARD_DIR/safe-env-inspect.mjs"`,
    `printf %s '${mergeB64}' | base64 -d | node - 2>/dev/null || echo "[paperclip-env-guard] settings merge skipped" >&2`,
  ].join("; ");
}
